Moving check chart test in test

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -42,3 +42,21 @@ jobs:
         with:
           command: install
           config: ct.yaml
+
+  check-chart-manifest-in-sync:
+    name: Check in sync
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Check helm template in sync
+        id: helm_template
+        run: |
+          helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml
+          if git diff --quiet && git diff --quiet --cached; then 
+            echo "✅ Manifests are in sync"; 
+          else 
+            echo "❌ Manifest update required. run "helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml" in the repository and push it;
+            exit 1
+          fi
